language: java

jdk:
    - openjdk11

dist: trusty

before_install:
    - wget --no-check-certificate http://tux.rainside.sk/apache//ant/binaries/apache-ant-1.10.6-bin.tar.gz
    - tar -xzvf apache-ant-1.10.6-bin.tar.gz
    - export PATH=`pwd`/apache-ant-1.10.6/bin:$PATH
    - echo $(ant -version)


install: 
    - cd MPCTestClient
    - ant -f build.xml -Dnb.internal.action.name=rebuild clean jar
    - cd ../MPCApplet/ 
    - ant -f jcbuild.xml build

script:
    - java -jar MPCTestClient/nbdist/MPCTestClient.jar
