language: java

jdk:
    - oraclejdk8
    - openjdk11

dist: trusty

before_install:
    - wget --no-check-certificate http://tux.rainside.sk/apache//ant/binaries/apache-ant-1.10.6-bin.tar.gz
    - tar -xzvf apache-ant-1.10.6-bin.tar.gz
    - export PATH=`pwd`/apache-ant-1.10.6/bin:$PATH
    - echo $(ant -version)


install:
    - export JAVA_HOME=$HOME/openjdk11 
    - cd MPCTestClient
    - ant
    - cd ../MPCApplet/
    - jdk_switcher use oraclejdk8 
    - ant -f jcbuild.xml build

script:
    - export JAVA_HOME=$HOME/openjdk11
    - java -jar out/artifacts/MPCTestClient_jar/MPCTestClient.jar
