language: java

jdk:
	- oraclejdk8

install: 
	 - MPCTestClient/ ant -f build.xml -Dnb.internal.action.name=rebuild clean jar
	 - MPCApplet/ ant -f jcbuild.xml build

script:
	- java -jar MPCTestClient/nbdist/MPCTestClient.jar
