language: java

jdk:
    - oraclejdk8

dist: trusty

before_install:
    # install Apache ant 1.10.6
    - wget --no-check-certificate http://tux.rainside.sk/apache//ant/binaries/apache-ant-1.10.6-bin.tar.gz
    - tar -xzvf apache-ant-1.10.6-bin.tar.gz
    - export PATH=`pwd`/apache-ant-1.10.6/bin:$PATH
    - echo $(ant -version)


install:
    - cd MPCTestClient
    - ant
    - cd ../MPCApplet/
    - ant -f jcbuild.xml build

script:
    - cd ../MPCTestClient
    - ClassPath="out/test/MPCTestClient:out/production/MPCTestClient:libs/*:out/production/MPCApplet"
    - java -ea -cp $ClassPath org.testng.TestNG test/testNGxmls/testng.xml
    # various tests using jcardsim have to be run sequentially
    - java -ea -noverify -cp $ClassPath org.testng.TestNG test/testNGxmls/testngSimCard1player.xml
    - java -ea -noverify -cp $ClassPath org.testng.TestNG test/testNGxmls/testngSimCard2players.xml
    - java -ea -noverify -cp $ClassPath org.testng.TestNG test/testNGxmls/testngSimCard3players.xml
    - java -ea -noverify -cp $ClassPath org.testng.TestNG test/testNGxmls/testngSimCard5players.xml
    - java -ea -noverify -cp $ClassPath org.testng.TestNG test/testNGxmls/testngSimCard10players.xml
    - java -ea -noverify -cp $ClassPath org.testng.TestNG test/testNGxmls/testngInsufficientPrivileges.xml
   
