language: java

jdk:
    - oraclejdk8


dist: trusty

before_install:
    - wget --no-check-certificate http://tux.rainside.sk/apache//ant/binaries/apache-ant-1.10.6-bin.tar.gz
    - tar -xzvf apache-ant-1.10.6-bin.tar.gz
    - export PATH=`pwd`/apache-ant-1.10.6/bin:$PATH
    - echo $(ant -version)


install:
    - cd MPCTestClient
    - ant
    - cd ../MPCApplet/
    - ant -f jcbuild.xml build

script:
    - cd ../MPCTestClient
    - ClassPath="out/test/MPCTestClient:out/production/MPCTestClient:libs/*:out/production/MPCApplet"
    - java -cp $ClassPath org.testng.TestNG test/testng.xml 
   
