language: java

jdk:
    - oraclejdk8

dist: trusty

before_install:
    # install Apache ant 1.10.7
    - wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.10.7-bin.tar.gz
    - tar -xzvf apache-ant-1.10.7-bin.tar.gz
    - export PATH=`pwd`/apache-ant-1.10.7/bin:$PATH
    - echo $(ant -version)


install:
    # build cap file
    - cd MPCApplet/
    - ant -f jcbuild.xml build
    - cd ..

script: 
    # because of jcardsim, tests have to be run sequentially
    - testFiles=$(grep --recursive --no-filename class MPCTestClient/src/test/java/mpcclient/ | awk '{ print $3 }')
    - echo "info: found tests: ${testFiles}"
    - for test in $testFiles; do ./gradlew -p MPCTestClient -Dtest.single=${testClass}; done
