language: java

jdk:
    - oraclejdk8

install: 
    - cd MPCTestClient
    - ant -f build.xml -Dnb.internal.action.name=rebuild clean jar
    - cd ../MPCApplet/ 
    - ant -f jcbuild.xml build

script:
    - java -jar MPCTestClient/nbdist/MPCTestClient.jar
